apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-hexagonal-arch
  labels:
    app: poc-hexagonal-arch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-hexagonal-arch
  template:
    metadata:
      labels:
        app: poc-hexagonal-arch
    spec:
      containers:
        - name: poc-hexagonal-arch
          image: tech-challenge-fase-1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: app-secret
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"